# Generated by Django 2.0.5 on 2018-08-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercises',
            name='max_rep',
        ),
        migrations.RemoveField(
            model_name='excercises',
            name='rounds_count',
        ),
        migrations.RemoveField(
            model_name='excercises',
            name='weight',
        ),
        migrations.AddField(
            model_name='rounds',
            name='max_rep',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rounds',
            name='rounds_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rounds',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
