# Generated by Django 2.0.5 on 2018-08-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180808_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rep', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='current_rep',
        ),
        migrations.AddField(
            model_name='excercises',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='round',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Rounds'),
        ),
    ]
