# Generated by Django 2.0.5 on 2018-08-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180808_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercises',
            name='description',
        ),
    ]
