# Generated by Django 2.0.5 on 2018-08-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_excercises_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='round',
        ),
        migrations.RenameField(
            model_name='rounds',
            old_name='max_rep',
            new_name='current_rep',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='rounds_count',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='weight',
        ),
        migrations.AddField(
            model_name='excercises',
            name='max_rep',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excercises',
            name='rounds_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excercises',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
