# Generated by Django 2.0.5 on 2018-08-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180808_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercises',
            name='weight',
        ),
        migrations.AddField(
            model_name='rounds',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
